"""Build a SageMaker deployment package on local disk.

This writes files. It does not talk to AWS: there is no boto3 import here and no
API call anywhere in the package. Uploading the archive and creating the
endpoint is left to the AWS CLI or the SageMaker SDK, and `next_steps()` prints
the commands.

The module this replaces was called an "AWS SageMaker Integration" and had
methods named deploy, _upload_model_to_s3, _create_endpoint,
_configure_auto_scaling and delete_endpoint. Each one logged a success message
under a comment reading "For now, we'll simulate it". Nothing reached AWS, so
`deploy()` returned an endpoint name for an endpoint that did not exist and
`get_endpoint_status()` reported it as live.
"""

import json
import logging
import os
import tarfile
from pathlib import Path
from typing import Any, Dict, List, Optional

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)

# On-demand SageMaker hosting prices, us-east-1, taken from the AWS pricing page
# on 2026-08-17. Hardcoded, so treat them as stale and check the current page.
# The old table silently fell back to the g4dn.xlarge price for any unrecognized
# instance type, which quoted the wrong number with no warning.
INSTANCE_HOURLY_USD = {
    "ml.m5.large": 0.115,
    "ml.m5.xlarge": 0.230,
    "ml.c5.xlarge": 0.204,
    "ml.g4dn.xlarge": 0.736,
    "ml.g4dn.2xlarge": 1.052,
    "ml.g4dn.4xlarge": 1.686,
    "ml.g5.xlarge": 1.408,
}
PRICES_AS_OF = "2026-08-17"
HOURS_PER_MONTH = 730

INFERENCE_SCRIPT = '''#!/usr/bin/env python3
"""SageMaker inference handlers for a TorchScript model.

Generated by llm_optimizer.packaging. The four function names below are the
handler contract SageMaker's PyTorch container looks for.
"""

import json
import os

import torch


def model_fn(model_dir):
    """Load the TorchScript model saved by the packaging step."""
    model = torch.jit.load(os.path.join(model_dir, "model.pt"), map_location="cpu")
    model.eval()
    return model


def input_fn(request_body, request_content_type):
    """Parse a JSON body of the form {"inputs": [[...]]} into a tensor."""
    if request_content_type != "application/json":
        raise ValueError("Unsupported content type: " + str(request_content_type))
    payload = json.loads(request_body)
    if "inputs" not in payload:
        raise ValueError('Request JSON must contain an "inputs" key.')
    return torch.tensor(payload["inputs"])


def predict_fn(input_tensor, model):
    """Run the model. No randomness, no placeholder."""
    with torch.no_grad():
        output = model(input_tensor)
    if isinstance(output, (tuple, list)):
        output = output[0]
    return output


def output_fn(prediction, accept):
    """Serialize the tensor back to JSON."""
    if accept != "application/json":
        raise ValueError("Unsupported accept type: " + str(accept))
    return json.dumps({"outputs": prediction.tolist()}), accept
'''

DOCKERFILE = """FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ml/code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model/ /opt/ml/model/
COPY inference.py .

ENV SAGEMAKER_PROGRAM=inference.py
ENV SAGEMAKER_SUBMIT_DIRECTORY=/opt/ml/code
ENV SAGEMAKER_CONTAINER_LOG_LEVEL=20
"""


class SageMakerPackageBuilder:
    """Write the files SageMaker's PyTorch container expects.

    Produces a directory holding the TorchScript model, an inference.py with the
    four handler functions, a requirements.txt and a Dockerfile, and optionally
    a model.tar.gz ready to upload.
    """

    def __init__(
        self,
        instance_type: str = "ml.g4dn.xlarge",
        min_instance_count: int = 1,
        max_instance_count: int = 1,
        region: str = "us-east-1",
    ):
        if min_instance_count < 1:
            raise ValueError("min_instance_count must be at least 1.")
        if max_instance_count < min_instance_count:
            raise ValueError(
                "max_instance_count cannot be below min_instance_count."
            )

        self.instance_type = instance_type
        self.min_instance_count = min_instance_count
        self.max_instance_count = max_instance_count
        self.region = region
        self.package_dir: Optional[Path] = None
        self.archive_path: Optional[Path] = None

    def build(
        self,
        model: nn.Module,
        example_inputs: Any,
        output_dir: str,
        extra_requirements: Optional[List[str]] = None,
        create_archive: bool = True,
    ) -> Path:
        """Write the package to `output_dir` and return its path.

        `example_inputs` is traced through the model to produce the TorchScript
        file. Tracing is what makes the saved artifact loadable by the generated
        inference.py without the original class definition, which is why it is
        required rather than optional.
        """
        package_dir = Path(output_dir)
        model_dir = package_dir / "model"
        model_dir.mkdir(parents=True, exist_ok=True)

        self._save_traced_model(model, example_inputs, model_dir)
        self._write_config(model, model_dir)

        (package_dir / "inference.py").write_text(INFERENCE_SCRIPT)
        os.chmod(package_dir / "inference.py", 0o755)

        requirements = ["torch>=2.0.0"] + list(extra_requirements or [])
        (package_dir / "requirements.txt").write_text("\n".join(requirements) + "\n")
        (package_dir / "Dockerfile").write_text(DOCKERFILE)

        self.package_dir = package_dir
        if create_archive:
            self.archive_path = self._create_archive(package_dir)

        logger.info("Deployment package written to %s", package_dir)
        return package_dir

    def _save_traced_model(
        self, model: nn.Module, example_inputs: Any, model_dir: Path
    ) -> Path:
        was_training = model.training
        model.eval()
        try:
            with torch.no_grad():
                traced = torch.jit.trace(model, example_inputs, strict=False)
        finally:
            model.train(was_training)

        path = model_dir / "model.pt"
        torch.jit.save(traced, str(path))
        return path

    def _write_config(self, model: nn.Module, model_dir: Path) -> Path:
        """Record what was packaged, using values read off the model."""
        dtypes = sorted({str(p.dtype) for p in model.parameters()})
        config = {
            "parameter_count": sum(p.numel() for p in model.parameters()),
            "parameter_dtypes": dtypes,
            "module_class": type(model).__name__,
            "instance_type": self.instance_type,
            "region": self.region,
            "torch_version": torch.__version__,
        }
        path = model_dir / "config.json"
        path.write_text(json.dumps(config, indent=2) + "\n")
        return path

    def _create_archive(self, package_dir: Path) -> Path:
        """Tar the package into model.tar.gz next to the directory.

        Paths inside the archive are relative to the package directory, because
        SageMaker extracts into /opt/ml and an absolute or nested prefix puts
        the files where the container will not find them.
        """
        archive_path = package_dir.parent / "model.tar.gz"
        with tarfile.open(archive_path, "w:gz") as tar:
            for item in sorted(package_dir.iterdir()):
                tar.add(item, arcname=item.name)
        logger.info("Created archive %s", archive_path)
        return archive_path

    def cost_estimate(self) -> Dict[str, Any]:
        """Monthly on-demand hosting cost from the static price table.

        Raises on an unknown instance type instead of quoting a default, and
        includes the date the prices were copied so a stale number is visible.
        """
        if self.instance_type not in INSTANCE_HOURLY_USD:
            raise KeyError(
                f"No price recorded for {self.instance_type}. Known types: "
                f"{', '.join(sorted(INSTANCE_HOURLY_USD))}. Check the AWS "
                f"pricing page and add it."
            )
        hourly = INSTANCE_HOURLY_USD[self.instance_type]
        return {
            "instance_type": self.instance_type,
            "region": self.region,
            "prices_as_of": PRICES_AS_OF,
            "hourly_usd": hourly,
            "monthly_usd_min": round(hourly * HOURS_PER_MONTH * self.min_instance_count, 2),
            "monthly_usd_max": round(hourly * HOURS_PER_MONTH * self.max_instance_count, 2),
            "note": "On-demand hosting only. Excludes data transfer and storage.",
        }

    def next_steps(self, bucket: str, role_arn: str, endpoint_name: str) -> List[str]:
        """The AWS CLI commands that would actually deploy the package.

        Returned as strings for the caller to review and run. This package does
        not execute them, so nothing here can create a billable resource by
        accident.
        """
        if self.archive_path is None:
            raise ValueError("Run build(create_archive=True) first.")

        s3_uri = f"s3://{bucket}/{endpoint_name}/model.tar.gz"
        return [
            f"aws s3 cp {self.archive_path} {s3_uri}",
            (
                f"aws sagemaker create-model --model-name {endpoint_name}-model "
                f"--execution-role-arn {role_arn} --region {self.region} "
                f"--primary-container Image=<pytorch-inference-image-uri>,"
                f"ModelDataUrl={s3_uri}"
            ),
            (
                f"aws sagemaker create-endpoint-config "
                f"--endpoint-config-name {endpoint_name}-config "
                f"--region {self.region} --production-variants "
                f"VariantName=default,ModelName={endpoint_name}-model,"
                f"InitialInstanceCount={self.min_instance_count},"
                f"InstanceType={self.instance_type}"
            ),
            (
                f"aws sagemaker create-endpoint --endpoint-name {endpoint_name} "
                f"--endpoint-config-name {endpoint_name}-config "
                f"--region {self.region}"
            ),
            (
                "# These create billable resources. Delete with: aws sagemaker "
                f"delete-endpoint --endpoint-name {endpoint_name}"
            ),
        ]
